console.log("avanzar uno");
console.log("quitar uno");
console.log("avanzar uno");
console.log("quitar uno");
console.log("avanzar uno");
console.log("quitar uno");
console.log("avanzar uno");
console.log("quitar uno");
console.log("girar 90 grados a la izquierda");
console.log("avanzar uno");
console.log("quitar uno");
console.log("avanzar uno");
console.log("quitar uno");
console.log("avanzar uno");